// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Torisho.Infrastructure;

#nullable disable

namespace Torisho.Infrastructure.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260302082758_FixedFlashcardRelationship")]
    partial class FixedFlashcardRelationship
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("RolePermissions", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("char(36)");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("RolePermissions", (string)null);
                });

            modelBuilder.Entity("Torisho.Domain.Common.LearningContent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("LevelId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("LevelId");

                    b.ToTable("LearningContent");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Torisho.Domain.Entities.DictionaryDomain.DictionaryEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ExamplesJson")
                        .HasColumnType("json");

                    b.Property<string>("Jlpt")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Keyword")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("MeaningsJson")
                        .HasColumnType("json");

                    b.Property<string>("Reading")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Jlpt")
                        .HasDatabaseName("IX_DictionaryEntries_Jlpt");

                    b.HasIndex("Keyword")
                        .HasDatabaseName("IX_DictionaryEntries_Keyword");

                    b.HasIndex("Reading")
                        .HasDatabaseName("IX_DictionaryEntries_Reading");

                    b.HasIndex("Jlpt", "Keyword")
                        .HasDatabaseName("IX_DictionaryEntries_Jlpt_Keyword");

                    b.ToTable("DictionaryEntries", (string)null);
                });

            modelBuilder.Entity("Torisho.Domain.Entities.DictionaryDomain.FlashCard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Back")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("DictionaryEntryId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Front")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("DictionaryEntryId");

                    b.HasIndex("UserId");

                    b.ToTable("FlashCard");
                });

            modelBuilder.Entity("Torisho.Domain.Entities.LearningDomain.Chapter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<Guid>("LevelId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<float>("RequiredProgressPercent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(100f);

                    b.Property<string>("ThumbnailUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("LevelId")
                        .HasDatabaseName("IX_Chapters_LevelId");

                    b.HasIndex("LevelId", "Order")
                        .HasDatabaseName("IX_Chapters_LevelId_Order");

                    b.ToTable("Chapters", (string)null);
                });

            modelBuilder.Entity("Torisho.Domain.Entities.LearningDomain.Lesson", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ChapterId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ContentId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<Guid?>("QuizId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ChapterId")
                        .HasDatabaseName("IX_Lessons_ChapterId");

                    b.HasIndex("ContentId")
                        .HasDatabaseName("IX_Lessons_ContentId");

                    b.HasIndex("QuizId")
                        .HasDatabaseName("IX_Lessons_QuizId");

                    b.HasIndex("ChapterId", "Order")
                        .HasDatabaseName("IX_Lessons_ChapterId_Order");

                    b.ToTable("Lessons", (string)null);
                });

            modelBuilder.Entity("Torisho.Domain.Entities.LearningDomain.Level", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<float>("RequiredProgressPercent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(100f);

                    b.Property<string>("ThumbnailUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("IX_Levels_Code");

                    b.HasIndex("Order")
                        .HasDatabaseName("IX_Levels_Order");

                    b.ToTable("Levels", (string)null);
                });

            modelBuilder.Entity("Torisho.Domain.Entities.NotificationDomain.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ActionUrl")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid?>("RelatedEntityId")
                        .HasColumnType("char(36)");

                    b.Property<string>("RelatedEntityType")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("UserId1")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId1");

                    b.ToTable("Notification");
                });

            modelBuilder.Entity("Torisho.Domain.Entities.ProgressDomain.ChapterProgress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ChapterId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CompletedLessonCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<float>("CompletionPercent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0f);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsUnlocked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("LevelId")
                        .HasColumnType("char(36)");

                    b.Property<int>("TotalLessonCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UnlockedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("ChapterId")
                        .HasDatabaseName("IX_ChapterProgresses_ChapterId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_ChapterProgresses_UserId");

                    b.HasIndex("UserId", "ChapterId")
                        .IsUnique()
                        .HasDatabaseName("IX_ChapterProgresses_UserId_ChapterId");

                    b.HasIndex("UserId", "IsUnlocked")
                        .HasDatabaseName("IX_ChapterProgresses_UserId_IsUnlocked");

                    b.HasIndex("UserId", "LevelId")
                        .HasDatabaseName("IX_ChapterProgresses_UserId_LevelId");

                    b.ToTable("ChapterProgresses", (string)null);
                });

            modelBuilder.Entity("Torisho.Domain.Entities.ProgressDomain.DailyActivities", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateOnly>("ActivityDate")
                        .HasColumnType("date");

                    b.Property<string>("ActivityDetailsJson")
                        .HasColumnType("json");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("DailyChallengeCompleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<float?>("DailyChallengeScore")
                        .HasColumnType("float");

                    b.Property<int>("FlashcardCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("GrammarCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("ListeningCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("QuizCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("ReadingCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("RoomCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("TotalMinutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("TotalPoints")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<int>("VocabularyCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("ActivityDate")
                        .HasDatabaseName("IX_DailyActivities_ActivityDate");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_DailyActivities_UserId");

                    b.HasIndex("UserId", "ActivityDate")
                        .IsUnique()
                        .HasDatabaseName("IX_DailyActivities_UserId_ActivityDate");

                    b.ToTable("DailyActivities", (string)null);
                });

            modelBuilder.Entity("Torisho.Domain.Entities.ProgressDomain.LearningProgress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<float>("GrammarProgress")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0f);

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("LevelId")
                        .HasColumnType("char(36)");

                    b.Property<float>("ListeningProgress")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0f);

                    b.Property<float>("ReadingProgress")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0f);

                    b.Property<float>("TotalProgress")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0f);

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<float>("VocabularyProgress")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0f);

                    b.HasKey("Id");

                    b.HasIndex("LevelId")
                        .HasDatabaseName("IX_LearningProgresses_LevelId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_LearningProgresses_UserId");

                    b.HasIndex("UserId", "LevelId")
                        .IsUnique()
                        .HasDatabaseName("IX_LearningProgresses_UserId_LevelId");

                    b.ToTable("LearningProgresses", (string)null);
                });

            modelBuilder.Entity("Torisho.Domain.Entities.QuizDomain.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<Guid>("QuizId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("QuizId")
                        .HasDatabaseName("IX_Questions_QuizId");

                    b.HasIndex("QuizId", "Order")
                        .HasDatabaseName("IX_Questions_QuizId_Order");

                    b.ToTable("Questions", (string)null);
                });

            modelBuilder.Entity("Torisho.Domain.Entities.QuizDomain.QuestionOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("OptionText")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId")
                        .HasDatabaseName("IX_QuestionOptions_QuestionId");

                    b.HasIndex("QuestionId", "IsCorrect")
                        .HasDatabaseName("IX_QuestionOptions_QuestionId_IsCorrect");

                    b.ToTable("QuestionOptions", (string)null);
                });

            modelBuilder.Entity("Torisho.Domain.Entities.QuizDomain.Quiz", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("TargetContentId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("TargetContentId")
                        .HasDatabaseName("IX_Quizzes_TargetContentId");

                    b.HasIndex("Type")
                        .HasDatabaseName("IX_Quizzes_Type");

                    b.ToTable("Quizzes", (string)null);
                });

            modelBuilder.Entity("Torisho.Domain.Entities.QuizDomain.QuizAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AttemptId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("QuizAttemptId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("SelectedOptionId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("AttemptId")
                        .HasDatabaseName("IX_QuizAnswers_AttemptId");

                    b.HasIndex("QuestionId")
                        .HasDatabaseName("IX_QuizAnswers_QuestionId");

                    b.HasIndex("QuizAttemptId");

                    b.HasIndex("SelectedOptionId");

                    b.ToTable("QuizAnswers", (string)null);
                });

            modelBuilder.Entity("Torisho.Domain.Entities.QuizDomain.QuizAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("QuizId")
                        .HasColumnType("char(36)");

                    b.Property<float>("Score")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0f);

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("QuizId")
                        .HasDatabaseName("IX_QuizAttempts_QuizId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_QuizAttempts_UserId");

                    b.HasIndex("QuizId", "Score")
                        .HasDatabaseName("IX_QuizAttempts_QuizId_Score");

                    b.HasIndex("UserId", "QuizId", "StartedAt")
                        .HasDatabaseName("IX_QuizAttempts_UserId_QuizId_StartedAt");

                    b.ToTable("QuizAttempts", (string)null);
                });

            modelBuilder.Entity("Torisho.Domain.Entities.RoomDomain.Room", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("AiCoachId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("RoomType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("ScheduledAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Transcript")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("RoomType")
                        .HasDatabaseName("IX_Rooms_RoomType");

                    b.HasIndex("ScheduledAt")
                        .HasDatabaseName("IX_Rooms_ScheduledAt");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Rooms_Status");

                    b.HasIndex("Status", "ScheduledAt")
                        .HasDatabaseName("IX_Rooms_Status_ScheduledAt");

                    b.ToTable("Rooms", (string)null);
                });

            modelBuilder.Entity("Torisho.Domain.Entities.RoomDomain.RoomMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsAiMessage")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("RoomId1")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("SenderId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.HasIndex("RoomId1");

                    b.HasIndex("SenderId");

                    b.ToTable("RoomMessage");
                });

            modelBuilder.Entity("Torisho.Domain.Entities.RoomDomain.RoomParticipant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("LeftAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("RoomId")
                        .HasDatabaseName("IX_RoomParticipants_RoomId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_RoomParticipants_UserId");

                    b.HasIndex("RoomId", "LeftAt")
                        .HasDatabaseName("IX_RoomParticipants_RoomId_LeftAt");

                    b.ToTable("RoomParticipants", (string)null);
                });

            modelBuilder.Entity("Torisho.Domain.Entities.UserDomain.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("IX_Permissions_Code");

                    b.ToTable("Permissions", (string)null);
                });

            modelBuilder.Entity("Torisho.Domain.Entities.UserDomain.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsRevoked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<string>("ReplacedByToken")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("IX_RefreshTokens_Token");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_RefreshTokens_UserId");

                    b.HasIndex("UserId", "IsRevoked", "ExpiresAt")
                        .HasDatabaseName("IX_RefreshTokens_UserId_IsRevoked_ExpiresAt");

                    b.ToTable("RefreshTokens", (string)null);
                });

            modelBuilder.Entity("Torisho.Domain.Entities.UserDomain.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_Roles_Name");

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("Torisho.Domain.Entities.UserDomain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<DateTime>("CreatedAt"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("UpdatedAt"));

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_Email");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Users_Status");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_Username");

                    b.HasIndex("Status", "CreatedAt")
                        .HasDatabaseName("IX_Users_Status_CreatedAt");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Torisho.Domain.Entities.VideoDomain.Subtitle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<float>("EndTime")
                        .HasColumnType("float");

                    b.Property<float>("StartTime")
                        .HasColumnType("float");

                    b.Property<string>("TextJp")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("TextVi")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("VideoLessonId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("VideoLessonId")
                        .HasDatabaseName("IX_Subtitles_VideoLessonId");

                    b.HasIndex("VideoLessonId", "StartTime")
                        .HasDatabaseName("IX_Subtitles_VideoLessonId_StartTime");

                    b.ToTable("Subtitles", (string)null);
                });

            modelBuilder.Entity("Torisho.Domain.Entities.VideoDomain.VideoProgress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<float>("CompletionPercent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0f);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsCompleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("LastWatchedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<float>("LastWatchedPosition")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0f);

                    b.Property<float>("TotalDuration")
                        .HasColumnType("float");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("VideoLessonId")
                        .HasColumnType("char(36)");

                    b.Property<float>("WatchedDuration")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0f);

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_VideoProgresses_UserId");

                    b.HasIndex("VideoLessonId")
                        .HasDatabaseName("IX_VideoProgresses_VideoLessonId");

                    b.HasIndex("UserId", "LastWatchedAt")
                        .HasDatabaseName("IX_VideoProgresses_UserId_LastWatchedAt");

                    b.HasIndex("UserId", "VideoLessonId")
                        .IsUnique()
                        .HasDatabaseName("IX_VideoProgresses_UserId_VideoLessonId");

                    b.ToTable("VideoProgresses", (string)null);
                });

            modelBuilder.Entity("UserRoles", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("char(36)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("VideoLessonVocabulary", b =>
                {
                    b.Property<Guid>("VideoLessonId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("VocabulariesId")
                        .HasColumnType("char(36)");

                    b.HasKey("VideoLessonId", "VocabulariesId");

                    b.HasIndex("VocabulariesId");

                    b.ToTable("VideoLessonVocabularies", (string)null);
                });

            modelBuilder.Entity("Torisho.Domain.Entities.ContentDomain.Kanji", b =>
                {
                    b.HasBaseType("Torisho.Domain.Common.LearningContent");

                    b.Property<string>("Character")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid?>("DictionaryEntryId")
                        .HasColumnType("char(36)");

                    b.Property<string>("KunYomi")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Meaning")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("OnYomi")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("StrokeCount")
                        .HasColumnType("int");

                    b.Property<string>("StrokeOrderGifUrl")
                        .HasColumnType("longtext");

                    b.HasIndex("DictionaryEntryId");

                    b.ToTable("Kanji");
                });

            modelBuilder.Entity("Torisho.Domain.Entities.ContentDomain.Vocabulary", b =>
                {
                    b.HasBaseType("Torisho.Domain.Common.LearningContent");

                    b.Property<Guid>("DictionaryEntryId")
                        .HasColumnType("char(36)");

                    b.HasIndex("DictionaryEntryId");

                    b.ToTable("Vocabulary");
                });

            modelBuilder.Entity("Torisho.Domain.Entities.VideoDomain.VideoLesson", b =>
                {
                    b.HasBaseType("Torisho.Domain.Common.LearningContent");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("ThumbnailUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("VideoUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.HasIndex("Order")
                        .HasDatabaseName("IX_VideoLessons_Order");

                    b.ToTable("VideoLessons", (string)null);
                });

            modelBuilder.Entity("RolePermissions", b =>
                {
                    b.HasOne("Torisho.Domain.Entities.UserDomain.Permission", null)
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Torisho.Domain.Entities.UserDomain.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Torisho.Domain.Common.LearningContent", b =>
                {
                    b.HasOne("Torisho.Domain.Entities.LearningDomain.Level", "Level")
                        .WithMany()
                        .HasForeignKey("LevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Level");
                });

            modelBuilder.Entity("Torisho.Domain.Entities.DictionaryDomain.FlashCard", b =>
                {
                    b.HasOne("Torisho.Domain.Entities.DictionaryDomain.DictionaryEntry", "DictionaryEntry")
                        .WithMany("FlashCards")
                        .HasForeignKey("DictionaryEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Torisho.Domain.Entities.UserDomain.User", "User")
                        .WithMany("FlashCards")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DictionaryEntry");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Torisho.Domain.Entities.LearningDomain.Chapter", b =>
                {
                    b.HasOne("Torisho.Domain.Entities.LearningDomain.Level", "Level")
                        .WithMany("Chapters")
                        .HasForeignKey("LevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Level");
                });

            modelBuilder.Entity("Torisho.Domain.Entities.LearningDomain.Lesson", b =>
                {
                    b.HasOne("Torisho.Domain.Entities.LearningDomain.Chapter", "Chapter")
                        .WithMany("Lessons")
                        .HasForeignKey("ChapterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Torisho.Domain.Common.LearningContent", "Content")
                        .WithMany()
                        .HasForeignKey("ContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Torisho.Domain.Entities.QuizDomain.Quiz", "Quiz")
                        .WithMany()
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Chapter");

                    b.Navigation("Content");

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("Torisho.Domain.Entities.NotificationDomain.Notification", b =>
                {
                    b.HasOne("Torisho.Domain.Entities.UserDomain.User", null)
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Torisho.Domain.Entities.UserDomain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId1");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Torisho.Domain.Entities.ProgressDomain.ChapterProgress", b =>
                {
                    b.HasOne("Torisho.Domain.Entities.LearningDomain.Chapter", "Chapter")
                        .WithMany()
                        .HasForeignKey("ChapterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Torisho.Domain.Entities.UserDomain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chapter");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Torisho.Domain.Entities.ProgressDomain.DailyActivities", b =>
                {
                    b.HasOne("Torisho.Domain.Entities.UserDomain.User", "User")
                        .WithMany("DailyActivities")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Torisho.Domain.Entities.ProgressDomain.LearningProgress", b =>
                {
                    b.HasOne("Torisho.Domain.Entities.LearningDomain.Level", "Level")
                        .WithMany("LearningProgresses")
                        .HasForeignKey("LevelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Torisho.Domain.Entities.UserDomain.User", "User")
                        .WithMany("LearningProgresses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Level");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Torisho.Domain.Entities.QuizDomain.Question", b =>
                {
                    b.HasOne("Torisho.Domain.Entities.QuizDomain.Quiz", "Quiz")
                        .WithMany("Questions")
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("Torisho.Domain.Entities.QuizDomain.QuestionOption", b =>
                {
                    b.HasOne("Torisho.Domain.Entities.QuizDomain.Question", "Question")
                        .WithMany("Options")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("Torisho.Domain.Entities.QuizDomain.QuizAnswer", b =>
                {
                    b.HasOne("Torisho.Domain.Entities.QuizDomain.QuizAttempt", "Attempt")
                        .WithMany()
                        .HasForeignKey("AttemptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Torisho.Domain.Entities.QuizDomain.Question", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Torisho.Domain.Entities.QuizDomain.QuizAttempt", null)
                        .WithMany("Answers")
                        .HasForeignKey("QuizAttemptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Torisho.Domain.Entities.QuizDomain.QuestionOption", "SelectedOption")
                        .WithMany()
                        .HasForeignKey("SelectedOptionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Attempt");

                    b.Navigation("Question");

                    b.Navigation("SelectedOption");
                });

            modelBuilder.Entity("Torisho.Domain.Entities.QuizDomain.QuizAttempt", b =>
                {
                    b.HasOne("Torisho.Domain.Entities.QuizDomain.Quiz", "Quiz")
                        .WithMany()
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Torisho.Domain.Entities.UserDomain.User", "User")
                        .WithMany("QuizAttempts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Quiz");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Torisho.Domain.Entities.RoomDomain.RoomMessage", b =>
                {
                    b.HasOne("Torisho.Domain.Entities.RoomDomain.Room", null)
                        .WithMany("Messages")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Torisho.Domain.Entities.RoomDomain.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId1");

                    b.HasOne("Torisho.Domain.Entities.UserDomain.User", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId");

                    b.Navigation("Room");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("Torisho.Domain.Entities.RoomDomain.RoomParticipant", b =>
                {
                    b.HasOne("Torisho.Domain.Entities.RoomDomain.Room", "Room")
                        .WithMany("Participants")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Torisho.Domain.Entities.UserDomain.User", "User")
                        .WithMany("RoomParticipants")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Torisho.Domain.Entities.UserDomain.RefreshToken", b =>
                {
                    b.HasOne("Torisho.Domain.Entities.UserDomain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Torisho.Domain.Entities.VideoDomain.Subtitle", b =>
                {
                    b.HasOne("Torisho.Domain.Entities.VideoDomain.VideoLesson", "VideoLesson")
                        .WithMany("Subtitles")
                        .HasForeignKey("VideoLessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VideoLesson");
                });

            modelBuilder.Entity("Torisho.Domain.Entities.VideoDomain.VideoProgress", b =>
                {
                    b.HasOne("Torisho.Domain.Entities.UserDomain.User", "User")
                        .WithMany("VideoProgresses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Torisho.Domain.Entities.VideoDomain.VideoLesson", "VideoLesson")
                        .WithMany("VideoProgresses")
                        .HasForeignKey("VideoLessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("VideoLesson");
                });

            modelBuilder.Entity("UserRoles", b =>
                {
                    b.HasOne("Torisho.Domain.Entities.UserDomain.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Torisho.Domain.Entities.UserDomain.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VideoLessonVocabulary", b =>
                {
                    b.HasOne("Torisho.Domain.Entities.VideoDomain.VideoLesson", null)
                        .WithMany()
                        .HasForeignKey("VideoLessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Torisho.Domain.Entities.ContentDomain.Vocabulary", null)
                        .WithMany()
                        .HasForeignKey("VocabulariesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Torisho.Domain.Entities.ContentDomain.Kanji", b =>
                {
                    b.HasOne("Torisho.Domain.Entities.DictionaryDomain.DictionaryEntry", null)
                        .WithMany("Kanjis")
                        .HasForeignKey("DictionaryEntryId");
                });

            modelBuilder.Entity("Torisho.Domain.Entities.ContentDomain.Vocabulary", b =>
                {
                    b.HasOne("Torisho.Domain.Entities.DictionaryDomain.DictionaryEntry", "DictionaryEntry")
                        .WithMany("Vocabularies")
                        .HasForeignKey("DictionaryEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DictionaryEntry");
                });

            modelBuilder.Entity("Torisho.Domain.Entities.VideoDomain.VideoLesson", b =>
                {
                    b.HasOne("Torisho.Domain.Common.LearningContent", null)
                        .WithOne()
                        .HasForeignKey("Torisho.Domain.Entities.VideoDomain.VideoLesson", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Torisho.Domain.Entities.DictionaryDomain.DictionaryEntry", b =>
                {
                    b.Navigation("FlashCards");

                    b.Navigation("Kanjis");

                    b.Navigation("Vocabularies");
                });

            modelBuilder.Entity("Torisho.Domain.Entities.LearningDomain.Chapter", b =>
                {
                    b.Navigation("Lessons");
                });

            modelBuilder.Entity("Torisho.Domain.Entities.LearningDomain.Level", b =>
                {
                    b.Navigation("Chapters");

                    b.Navigation("LearningProgresses");
                });

            modelBuilder.Entity("Torisho.Domain.Entities.QuizDomain.Question", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("Torisho.Domain.Entities.QuizDomain.Quiz", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("Torisho.Domain.Entities.QuizDomain.QuizAttempt", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("Torisho.Domain.Entities.RoomDomain.Room", b =>
                {
                    b.Navigation("Messages");

                    b.Navigation("Participants");
                });

            modelBuilder.Entity("Torisho.Domain.Entities.UserDomain.User", b =>
                {
                    b.Navigation("DailyActivities");

                    b.Navigation("FlashCards");

                    b.Navigation("LearningProgresses");

                    b.Navigation("Notifications");

                    b.Navigation("QuizAttempts");

                    b.Navigation("RoomParticipants");

                    b.Navigation("VideoProgresses");
                });

            modelBuilder.Entity("Torisho.Domain.Entities.VideoDomain.VideoLesson", b =>
                {
                    b.Navigation("Subtitles");

                    b.Navigation("VideoProgresses");
                });
#pragma warning restore 612, 618
        }
    }
}
