// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Torisho.Infrastructure;

#nullable disable

namespace Torisho.Infrastructure.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Torisho.Domain.Common.LearningContent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("varchar(21)");

                    b.Property<Guid>("LevelId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("LevelId");

                    b.ToTable("LearningContent");

                    b.HasDiscriminator().HasValue("LearningContent");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Torisho.Domain.Entities.DictionaryDomain.DictionaryEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ExamplesJson")
                        .HasColumnType("longtext");

                    b.Property<int>("Jlpt")
                        .HasColumnType("int");

                    b.Property<string>("Keyword")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MeaningsJson")
                        .HasColumnType("longtext");

                    b.Property<string>("Reading")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("DictionaryEntry");
                });

            modelBuilder.Entity("Torisho.Domain.Entities.DictionaryDomain.FlashCard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Back")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("DictionaryEntryId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Front")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("DictionaryEntryId");

                    b.HasIndex("UserId");

                    b.ToTable("FlashCard");
                });

            modelBuilder.Entity("Torisho.Domain.Entities.LearningDomain.Chapter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<Guid>("LevelId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<float>("RequiredProgressPercent")
                        .HasColumnType("float");

                    b.Property<string>("ThumbnailUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("LevelId");

                    b.ToTable("Chapter");
                });

            modelBuilder.Entity("Torisho.Domain.Entities.LearningDomain.Lesson", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ChapterId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ContentId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<Guid?>("QuizId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ChapterId");

                    b.HasIndex("ContentId");

                    b.HasIndex("QuizId");

                    b.ToTable("Lesson");
                });

            modelBuilder.Entity("Torisho.Domain.Entities.LearningDomain.Level", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("Code")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<float>("RequiredProgressPercent")
                        .HasColumnType("float");

                    b.Property<string>("ThumbnailUrl")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Level");
                });

            modelBuilder.Entity("Torisho.Domain.Entities.NotificationDomain.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ActionUrl")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid?>("RelatedEntityId")
                        .HasColumnType("char(36)");

                    b.Property<string>("RelatedEntityType")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notification");
                });

            modelBuilder.Entity("Torisho.Domain.Entities.ProgressDomain.DailyActivities", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateOnly>("ActivityDate")
                        .HasColumnType("date");

                    b.Property<string>("ActivityDetailsJson")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("DailyChallengeCompleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<float?>("DailyChallengeScore")
                        .HasColumnType("float");

                    b.Property<int>("FlashcardCount")
                        .HasColumnType("int");

                    b.Property<int>("GrammarCount")
                        .HasColumnType("int");

                    b.Property<int>("ListeningCount")
                        .HasColumnType("int");

                    b.Property<int>("QuizCount")
                        .HasColumnType("int");

                    b.Property<int>("ReadingCount")
                        .HasColumnType("int");

                    b.Property<int>("RoomCount")
                        .HasColumnType("int");

                    b.Property<int>("TotalMinutes")
                        .HasColumnType("int");

                    b.Property<int>("TotalPoints")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<int>("VocabularyCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("DailyActivities");
                });

            modelBuilder.Entity("Torisho.Domain.Entities.ProgressDomain.LearningProgress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<float>("GrammarProgress")
                        .HasColumnType("float");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("LevelId")
                        .HasColumnType("char(36)");

                    b.Property<float>("ListeningProgress")
                        .HasColumnType("float");

                    b.Property<float>("ReadingProgress")
                        .HasColumnType("float");

                    b.Property<float>("TotalProgress")
                        .HasColumnType("float");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<float>("VocabularyProgress")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("LevelId");

                    b.HasIndex("UserId");

                    b.ToTable("LearningProgress");
                });

            modelBuilder.Entity("Torisho.Domain.Entities.QuizDomain.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<Guid>("QuizId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("QuizId");

                    b.ToTable("Question");
                });

            modelBuilder.Entity("Torisho.Domain.Entities.QuizDomain.QuestionOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("OptionText")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("QuestionOption");
                });

            modelBuilder.Entity("Torisho.Domain.Entities.QuizDomain.Quiz", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("TargetContentId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Quiz");
                });

            modelBuilder.Entity("Torisho.Domain.Entities.QuizDomain.QuizAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AttemptId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("SelectedOptionId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("AttemptId");

                    b.HasIndex("QuestionId");

                    b.HasIndex("SelectedOptionId");

                    b.ToTable("QuizAnswer");
                });

            modelBuilder.Entity("Torisho.Domain.Entities.QuizDomain.QuizAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("QuizId")
                        .HasColumnType("char(36)");

                    b.Property<float>("Score")
                        .HasColumnType("float");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("QuizId");

                    b.HasIndex("UserId");

                    b.ToTable("QuizAttempt");
                });

            modelBuilder.Entity("Torisho.Domain.Entities.RoomDomain.Room", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("AiCoachId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("RoomType")
                        .HasColumnType("int");

                    b.Property<DateTime>("ScheduledAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Transcript")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Room");
                });

            modelBuilder.Entity("Torisho.Domain.Entities.RoomDomain.RoomMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsAiMessage")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("SenderId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.HasIndex("SenderId");

                    b.ToTable("RoomMessage");
                });

            modelBuilder.Entity("Torisho.Domain.Entities.RoomDomain.RoomParticipant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("LeftAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.HasIndex("UserId");

                    b.ToTable("RoomParticipant");
                });

            modelBuilder.Entity("Torisho.Domain.Entities.UserDomain.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid?>("RoleId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Permission");
                });

            modelBuilder.Entity("Torisho.Domain.Entities.UserDomain.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsRevoked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<string>("ReplacedByToken")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("IX_RefreshTokens_Token");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_RefreshTokens_UserId");

                    b.HasIndex("UserId", "IsRevoked", "ExpiresAt")
                        .HasDatabaseName("IX_RefreshTokens_UserId_IsRevoked_ExpiresAt");

                    b.ToTable("RefreshTokens", (string)null);
                });

            modelBuilder.Entity("Torisho.Domain.Entities.UserDomain.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Role");
                });

            modelBuilder.Entity("Torisho.Domain.Entities.UserDomain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("Torisho.Domain.Entities.VideoDomain.Subtitle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<float>("EndTime")
                        .HasColumnType("float");

                    b.Property<float>("StartTime")
                        .HasColumnType("float");

                    b.Property<string>("TextJp")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TextVi")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("VideoLessonId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("VideoLessonId");

                    b.ToTable("Subtitle");
                });

            modelBuilder.Entity("Torisho.Domain.Entities.VideoDomain.VideoProgress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<float>("CompletionPercent")
                        .HasColumnType("float");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("LastWatchedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<float>("LastWatchedPosition")
                        .HasColumnType("float");

                    b.Property<float>("TotalDuration")
                        .HasColumnType("float");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("VideoLessonId")
                        .HasColumnType("char(36)");

                    b.Property<float>("WatchedDuration")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("VideoLessonId");

                    b.ToTable("VideoProgress");
                });

            modelBuilder.Entity("Torisho.Domain.Entities.ContentDomain.Kanji", b =>
                {
                    b.HasBaseType("Torisho.Domain.Common.LearningContent");

                    b.Property<string>("Character")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid?>("DictionaryEntryId")
                        .HasColumnType("char(36)");

                    b.Property<string>("KunYomi")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Meaning")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("OnYomi")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("StrokeCount")
                        .HasColumnType("int");

                    b.Property<string>("StrokeOrderGifUrl")
                        .HasColumnType("longtext");

                    b.HasIndex("DictionaryEntryId");

                    b.HasDiscriminator().HasValue("Kanji");
                });

            modelBuilder.Entity("Torisho.Domain.Entities.ContentDomain.Vocabulary", b =>
                {
                    b.HasBaseType("Torisho.Domain.Common.LearningContent");

                    b.Property<Guid>("DictionaryEntryId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("VideoLessonId")
                        .HasColumnType("char(36)");

                    b.HasIndex("DictionaryEntryId");

                    b.HasIndex("VideoLessonId");

                    b.ToTable("LearningContent", t =>
                        {
                            t.Property("DictionaryEntryId")
                                .HasColumnName("Vocabulary_DictionaryEntryId");
                        });

                    b.HasDiscriminator().HasValue("Vocabulary");
                });

            modelBuilder.Entity("Torisho.Domain.Entities.VideoDomain.VideoLesson", b =>
                {
                    b.HasBaseType("Torisho.Domain.Common.LearningContent");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("ThumbnailUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("VideoUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasDiscriminator().HasValue("VideoLesson");
                });

            modelBuilder.Entity("Torisho.Domain.Common.LearningContent", b =>
                {
                    b.HasOne("Torisho.Domain.Entities.LearningDomain.Level", "Level")
                        .WithMany()
                        .HasForeignKey("LevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Level");
                });

            modelBuilder.Entity("Torisho.Domain.Entities.DictionaryDomain.FlashCard", b =>
                {
                    b.HasOne("Torisho.Domain.Entities.DictionaryDomain.DictionaryEntry", "DictionaryEntry")
                        .WithMany("FlashCards")
                        .HasForeignKey("DictionaryEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Torisho.Domain.Entities.UserDomain.User", "User")
                        .WithMany("FlashCards")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DictionaryEntry");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Torisho.Domain.Entities.LearningDomain.Chapter", b =>
                {
                    b.HasOne("Torisho.Domain.Entities.LearningDomain.Level", "Level")
                        .WithMany("Chapters")
                        .HasForeignKey("LevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Level");
                });

            modelBuilder.Entity("Torisho.Domain.Entities.LearningDomain.Lesson", b =>
                {
                    b.HasOne("Torisho.Domain.Entities.LearningDomain.Chapter", "Chapter")
                        .WithMany("Lessons")
                        .HasForeignKey("ChapterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Torisho.Domain.Common.LearningContent", "Content")
                        .WithMany()
                        .HasForeignKey("ContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Torisho.Domain.Entities.QuizDomain.Quiz", "Quiz")
                        .WithMany()
                        .HasForeignKey("QuizId");

                    b.Navigation("Chapter");

                    b.Navigation("Content");

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("Torisho.Domain.Entities.NotificationDomain.Notification", b =>
                {
                    b.HasOne("Torisho.Domain.Entities.UserDomain.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Torisho.Domain.Entities.ProgressDomain.DailyActivities", b =>
                {
                    b.HasOne("Torisho.Domain.Entities.UserDomain.User", "User")
                        .WithMany("DailyActivities")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Torisho.Domain.Entities.ProgressDomain.LearningProgress", b =>
                {
                    b.HasOne("Torisho.Domain.Entities.LearningDomain.Level", "Level")
                        .WithMany("LearningProgresses")
                        .HasForeignKey("LevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Torisho.Domain.Entities.UserDomain.User", "User")
                        .WithMany("LearningProgresses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Level");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Torisho.Domain.Entities.QuizDomain.Question", b =>
                {
                    b.HasOne("Torisho.Domain.Entities.QuizDomain.Quiz", "Quiz")
                        .WithMany("Questions")
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("Torisho.Domain.Entities.QuizDomain.QuestionOption", b =>
                {
                    b.HasOne("Torisho.Domain.Entities.QuizDomain.Question", "Question")
                        .WithMany("Options")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("Torisho.Domain.Entities.QuizDomain.QuizAnswer", b =>
                {
                    b.HasOne("Torisho.Domain.Entities.QuizDomain.QuizAttempt", "Attempt")
                        .WithMany("Answers")
                        .HasForeignKey("AttemptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Torisho.Domain.Entities.QuizDomain.Question", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Torisho.Domain.Entities.QuizDomain.QuestionOption", "SelectedOption")
                        .WithMany()
                        .HasForeignKey("SelectedOptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attempt");

                    b.Navigation("Question");

                    b.Navigation("SelectedOption");
                });

            modelBuilder.Entity("Torisho.Domain.Entities.QuizDomain.QuizAttempt", b =>
                {
                    b.HasOne("Torisho.Domain.Entities.QuizDomain.Quiz", "Quiz")
                        .WithMany()
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Torisho.Domain.Entities.UserDomain.User", "User")
                        .WithMany("QuizAttempts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quiz");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Torisho.Domain.Entities.RoomDomain.RoomMessage", b =>
                {
                    b.HasOne("Torisho.Domain.Entities.RoomDomain.Room", "Room")
                        .WithMany("Messages")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Torisho.Domain.Entities.UserDomain.User", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId");

                    b.Navigation("Room");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("Torisho.Domain.Entities.RoomDomain.RoomParticipant", b =>
                {
                    b.HasOne("Torisho.Domain.Entities.RoomDomain.Room", "Room")
                        .WithMany("Participants")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Torisho.Domain.Entities.UserDomain.User", "User")
                        .WithMany("RoomParticipants")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Torisho.Domain.Entities.UserDomain.Permission", b =>
                {
                    b.HasOne("Torisho.Domain.Entities.UserDomain.Role", null)
                        .WithMany("Permissions")
                        .HasForeignKey("RoleId");
                });

            modelBuilder.Entity("Torisho.Domain.Entities.UserDomain.RefreshToken", b =>
                {
                    b.HasOne("Torisho.Domain.Entities.UserDomain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Torisho.Domain.Entities.UserDomain.Role", b =>
                {
                    b.HasOne("Torisho.Domain.Entities.UserDomain.User", null)
                        .WithMany("Roles")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("Torisho.Domain.Entities.VideoDomain.Subtitle", b =>
                {
                    b.HasOne("Torisho.Domain.Entities.VideoDomain.VideoLesson", "VideoLesson")
                        .WithMany("Subtitles")
                        .HasForeignKey("VideoLessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VideoLesson");
                });

            modelBuilder.Entity("Torisho.Domain.Entities.VideoDomain.VideoProgress", b =>
                {
                    b.HasOne("Torisho.Domain.Entities.UserDomain.User", "User")
                        .WithMany("VideoProgresses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Torisho.Domain.Entities.VideoDomain.VideoLesson", "VideoLesson")
                        .WithMany("VideoProgresses")
                        .HasForeignKey("VideoLessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("VideoLesson");
                });

            modelBuilder.Entity("Torisho.Domain.Entities.ContentDomain.Kanji", b =>
                {
                    b.HasOne("Torisho.Domain.Entities.DictionaryDomain.DictionaryEntry", null)
                        .WithMany("Kanjis")
                        .HasForeignKey("DictionaryEntryId");
                });

            modelBuilder.Entity("Torisho.Domain.Entities.ContentDomain.Vocabulary", b =>
                {
                    b.HasOne("Torisho.Domain.Entities.DictionaryDomain.DictionaryEntry", "DictionaryEntry")
                        .WithMany("Vocabularies")
                        .HasForeignKey("DictionaryEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Torisho.Domain.Entities.VideoDomain.VideoLesson", null)
                        .WithMany("Vocabularies")
                        .HasForeignKey("VideoLessonId");

                    b.Navigation("DictionaryEntry");
                });

            modelBuilder.Entity("Torisho.Domain.Entities.DictionaryDomain.DictionaryEntry", b =>
                {
                    b.Navigation("FlashCards");

                    b.Navigation("Kanjis");

                    b.Navigation("Vocabularies");
                });

            modelBuilder.Entity("Torisho.Domain.Entities.LearningDomain.Chapter", b =>
                {
                    b.Navigation("Lessons");
                });

            modelBuilder.Entity("Torisho.Domain.Entities.LearningDomain.Level", b =>
                {
                    b.Navigation("Chapters");

                    b.Navigation("LearningProgresses");
                });

            modelBuilder.Entity("Torisho.Domain.Entities.QuizDomain.Question", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("Torisho.Domain.Entities.QuizDomain.Quiz", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("Torisho.Domain.Entities.QuizDomain.QuizAttempt", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("Torisho.Domain.Entities.RoomDomain.Room", b =>
                {
                    b.Navigation("Messages");

                    b.Navigation("Participants");
                });

            modelBuilder.Entity("Torisho.Domain.Entities.UserDomain.Role", b =>
                {
                    b.Navigation("Permissions");
                });

            modelBuilder.Entity("Torisho.Domain.Entities.UserDomain.User", b =>
                {
                    b.Navigation("DailyActivities");

                    b.Navigation("FlashCards");

                    b.Navigation("LearningProgresses");

                    b.Navigation("Notifications");

                    b.Navigation("QuizAttempts");

                    b.Navigation("Roles");

                    b.Navigation("RoomParticipants");

                    b.Navigation("VideoProgresses");
                });

            modelBuilder.Entity("Torisho.Domain.Entities.VideoDomain.VideoLesson", b =>
                {
                    b.Navigation("Subtitles");

                    b.Navigation("VideoProgresses");

                    b.Navigation("Vocabularies");
                });
#pragma warning restore 612, 618
        }
    }
}
